"""add_gstin_to_addresses

Revision ID: 7faf47557960
Revises: 822cc8a9a30f
Create Date: 2026-06-02 09:56:26.621082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7faf47557960'
down_revision: Union[str, Sequence[str], None] = '822cc8a9a30f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('gstin', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'gstin')
    # ### end Alembic commands ###
