"""add_pickup_tables

Revision ID: b1bd54077869
Revises: 2dc7f2258368
Create Date: 2025-12-28 08:58:25.148009

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b1bd54077869'
down_revision: Union[str, Sequence[str], None] = '2dc7f2258368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def drop_enums():
    op.execute("DROP TYPE IF EXISTS shipmenttype;")
    op.execute("DROP TYPE IF EXISTS servicetype;")
    op.execute("DROP TYPE IF EXISTS paymentmode;")
    op.execute("DROP TYPE IF EXISTS pickupstatus;")
    op.execute("DROP TYPE IF EXISTS documenttype;")

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # drop all the enums 
    drop_enums()

    op.create_table('addresses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('address_line1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_line2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('landmark', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('pincode', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_city'), 'addresses', ['city'], unique=False)
    op.create_index(op.f('ix_addresses_pincode'), 'addresses', ['pincode'], unique=False)
    op.create_index(op.f('ix_addresses_tenant_id'), 'addresses', ['tenant_id'], unique=False)
    op.create_table('pickups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('order_reference_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('tracking_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shipment_type', sa.Enum('FORWARD', 'REVERSE', name='shipmenttype'), nullable=False),
    sa.Column('service_type', sa.Enum('SURFACE', 'EXPRESS', name='servicetype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'ASSIGNED', 'IN_TRANSIT', 'COMPLETED', 'CANCELLED', 'RTO_INITIATED', name='pickupstatus'), nullable=False),
    sa.Column('product_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shipment_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reason_for_return', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requested_pickup_date', sa.Date(), nullable=False),
    sa.Column('pickup_address_id', sa.Uuid(), nullable=False),
    sa.Column('delivery_address_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['pickup_address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pickups_order_reference_id'), 'pickups', ['order_reference_id'], unique=False)
    op.create_index(op.f('ix_pickups_tenant_id'), 'pickups', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_pickups_tracking_id'), 'pickups', ['tracking_id'], unique=False)
    op.create_table('package_details',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pickup_id', sa.Uuid(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('breadth', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('box_count', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_fragile', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_details',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pickup_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('payment_mode', sa.Enum('PREPAID', 'COD', name='paymentmode'), nullable=False),
    sa.Column('declared_value', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('hsn_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('eway_bill_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pickup_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pickup_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.Enum('GST_INVOICE', 'EWAY_BILL', 'DELIVERY_CHALLAN', 'DECLARATION', 'BOX_PHOTO', 'LABEL_IMAGE', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pickup_id'], ['pickups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pickup_documents')
    op.drop_table('payment_details')
    op.drop_table('package_details')
    op.drop_index(op.f('ix_pickups_tracking_id'), table_name='pickups')
    op.drop_index(op.f('ix_pickups_tenant_id'), table_name='pickups')
    op.drop_index(op.f('ix_pickups_order_reference_id'), table_name='pickups')
    op.drop_table('pickups')
    op.drop_index(op.f('ix_addresses_tenant_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_pincode'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_city'), table_name='addresses')
    op.drop_table('addresses')
    # drop all the enums 
    drop_enums()
    # ### end Alembic commands ###
