"""B2B schema alignment

Revision ID: c2a411a349d3
Revises: 4bf316b4ecbb
Create Date: 2026-06-14 21:30:25.367371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c2a411a349d3'
down_revision: Union[str, Sequence[str], None] = '4bf316b4ecbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Manual enum alterations
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'PO_COPY'")
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'KYC'")
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'REGULATORY_FORM'")
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'PHOTO_ID'")
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'ASN'")
    op.execute("ALTER TYPE documenttype ADD VALUE IF NOT EXISTS 'E_INVOICE_QR'")
    op.execute("ALTER TYPE ndrexceptionreason ADD VALUE IF NOT EXISTS 'CUSTOMER_UNAVAILABLE'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_details', sa.Column('child_awb_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('payment_details', sa.Column('invoice_numbers', sa.JSON(), nullable=True))
    op.add_column('payment_details', sa.Column('eway_bill_numbers', sa.JSON(), nullable=True))
    op.add_column('payment_details', sa.Column('chargeable_weight', sa.Float(), nullable=False, server_default='0.0'))
    
    # Safely migrate existing legacy data into the new JSON array columns before dropping
    op.execute("UPDATE payment_details SET invoice_numbers = json_build_array(invoice_number) WHERE invoice_number IS NOT NULL AND invoice_number != ''")
    op.execute("UPDATE payment_details SET eway_bill_numbers = json_build_array(eway_bill_number) WHERE eway_bill_number IS NOT NULL AND eway_bill_number != ''")

    op.drop_column('payment_details', 'eway_bill_number')
    op.drop_column('payment_details', 'invoice_number')
    ndrexceptionreason = sa.Enum('DOCUMENT_NEEDED', 'APPOINTMENT_NEEDED', 'SHORT_SHIPMENT', 'CUSTOMER_UNAVAILABLE', name='ndrexceptionreason')
    ndrexceptionreason.create(op.get_bind(), checkfirst=True)
    op.add_column('pickups', sa.Column('ndr_reason', ndrexceptionreason, nullable=True))
    op.add_column('pickups', sa.Column('po_number', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('pickups', sa.Column('po_date', sa.Date(), nullable=True))
    op.add_column('pickups', sa.Column('appointment_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('pickups', sa.Column('appointment_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pickups', sa.Column('appointment_end', sa.DateTime(timezone=True), nullable=True))
    pickupstrategy = sa.Enum('DEFAULT', 'DEDICATED', 'CONSOLIDATED', name='pickupstrategy')
    pickupstrategy.create(op.get_bind(), checkfirst=True)
    op.add_column('pickups', sa.Column('pickup_strategy', pickupstrategy, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pickups', 'pickup_strategy')
    op.drop_column('pickups', 'appointment_end')
    op.drop_column('pickups', 'appointment_start')
    op.drop_column('pickups', 'appointment_id')
    op.drop_column('pickups', 'po_date')
    op.drop_column('pickups', 'po_number')
    op.drop_column('pickups', 'ndr_reason')
    op.add_column('payment_details', sa.Column('invoice_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('payment_details', sa.Column('eway_bill_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('payment_details', 'chargeable_weight')
    op.drop_column('payment_details', 'eway_bill_numbers')
    op.drop_column('payment_details', 'invoice_numbers')
    op.drop_column('package_details', 'child_awb_number')
    # ### end Alembic commands ###
