"""add_shipment_activity_table

Revision ID: c730485a140f
Revises: fa278b7b0019
Create Date: 2026-02-02 18:50:56.660051

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c730485a140f"
down_revision: Union[str, Sequence[str], None] = "fa278b7b0019"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shipment_activities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pickup_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column(
            "activity_type",
            sa.Enum(
                "STATUS_CHANGE",
                "INFO_UPDATE",
                "COMMENT",
                "EXCEPTION",
                name="activitytype",
            ),
            nullable=False,
        ),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("diff", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pickup_id"],
            ["pickups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "pickups",
        sa.Column(
            "latest_status_comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pickups", "latest_status_comment")
    op.drop_table("shipment_activities")
    op.execute("DROP TYPE IF EXISTS activitytype;")
    # ### end Alembic commands ###
