"""remove_shipment_description

Revision ID: d5f000c3f65a
Revises: 216a08d0513c
Create Date: 2026-05-31 13:34:59.386368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f000c3f65a'
down_revision: Union[str, Sequence[str], None] = '216a08d0513c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pickups', 'shipment_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pickups', sa.Column('shipment_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
