"""option_a_hybrid_financials

Revision ID: e7f4d6d62064
Revises: 9c24638bfcf2
Create Date: 2026-06-01 19:01:15.991983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f4d6d62064'
down_revision: Union[str, Sequence[str], None] = '9c24638bfcf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add columns as nullable=True first
    op.add_column('payment_details', sa.Column('add_shipping_to_cod', sa.Boolean(), nullable=True))
    op.add_column('payment_details', sa.Column('shipment_value', sa.Float(), nullable=True))
    op.add_column('payment_details', sa.Column('shipment_tax_value', sa.Float(), nullable=True))
    op.add_column('payment_details', sa.Column('shipment_total_value', sa.Float(), nullable=True))

    # 2. Backfill existing rows from declared_value
    op.execute("UPDATE payment_details SET add_shipping_to_cod = FALSE WHERE add_shipping_to_cod IS NULL")
    op.execute("UPDATE payment_details SET shipment_value = COALESCE(declared_value, 0.0) WHERE shipment_value IS NULL")
    op.execute("UPDATE payment_details SET shipment_tax_value = 0.0 WHERE shipment_tax_value IS NULL")
    op.execute("UPDATE payment_details SET shipment_total_value = COALESCE(declared_value, 0.0) WHERE shipment_total_value IS NULL")

    # 3. Alter columns to NOT NULL
    op.alter_column('payment_details', 'add_shipping_to_cod', nullable=False)
    op.alter_column('payment_details', 'shipment_value', nullable=False)
    op.alter_column('payment_details', 'shipment_tax_value', nullable=False)
    op.alter_column('payment_details', 'shipment_total_value', nullable=False)

    # 4. Safe drop declared_value
    op.drop_column('payment_details', 'declared_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_details', sa.Column('declared_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('payment_details', 'shipment_total_value')
    op.drop_column('payment_details', 'shipment_tax_value')
    op.drop_column('payment_details', 'shipment_value')
    op.drop_column('payment_details', 'add_shipping_to_cod')
    # ### end Alembic commands ###
